// Data contoh kelas — seri "Mahir AI" dari Melek Digital
const CLASSES = [
  {
    id: "mahir-ai-dasar",
    title: "Mahir AI dari Nol",
    category: "Dasar AI",
    level: "Pemula",
    price: 249000,
    oldPrice: 399000,
    rating: 4.9,
    reviews: 812,
    students: 5230,
    duration: "6 jam",
    modules: 8,
    desc: "Kelas fondasi untuk yang belum pernah sama sekali menyentuh AI. Mulai dari apa itu AI, cara kerja ChatGPT, sampai bisa pakai AI setiap hari tanpa bingung.",
    popular: true,
  },
  {
    id: "chatgpt-produktif",
    title: "ChatGPT untuk Kerja Sehari-hari",
    category: "Produktivitas",
    level: "Pemula",
    price: 199000,
    oldPrice: 299000,
    rating: 4.8,
    reviews: 634,
    students: 4110,
    duration: "4.5 jam",
    modules: 6,
    desc: "Pakai ChatGPT untuk bikin email, laporan, ide, sampai jadwal kerja. Cocok untuk karyawan dan pemilik usaha yang mau lebih cepat kerjanya.",
    popular: true,
  },
  {
    id: "prompt-writing",
    title: "Seni Menulis Prompt (Prompt Writing)",
    category: "Skill Inti",
    level: "Menengah",
    price: 279000,
    oldPrice: 349000,
    rating: 4.9,
    reviews: 401,
    students: 2870,
    duration: "5 jam",
    modules: 7,
    desc: "Belajar menulis perintah ke AI supaya hasilnya tepat sasaran dari kali pertama. Kunci supaya AI 'ngerti' apa yang kamu mau.",
    popular: true,
  },
  {
    id: "ai-konten-sosmed",
    title: "AI untuk Konten Media Sosial",
    category: "Konten & Media",
    level: "Pemula",
    price: 229000,
    oldPrice: 329000,
    rating: 4.7,
    reviews: 512,
    students: 3320,
    duration: "5 jam",
    modules: 7,
    desc: "Bikin caption, ide konten, sampai gambar untuk Instagram dan TikTok pakai bantuan AI, tanpa perlu jadi desainer.",
    popular: false,
  },
  {
    id: "ai-gambar",
    title: "Membuat Gambar dengan AI (Midjourney & DALL·E)",
    category: "Kreatif",
    level: "Menengah",
    price: 259000,
    oldPrice: 379000,
    rating: 4.8,
    reviews: 288,
    students: 1950,
    duration: "6.5 jam",
    modules: 9,
    desc: "Dari teks jadi gambar. Pelajari cara menghasilkan ilustrasi, poster, dan mockup produk hanya dengan deskripsi kata.",
    popular: false,
  },
  {
    id: "ai-umkm",
    title: "AI untuk UMKM: Jualan Lebih Gampang",
    category: "Bisnis",
    level: "Pemula",
    price: 219000,
    oldPrice: 299000,
    rating: 4.8,
    reviews: 356,
    students: 2410,
    duration: "4 jam",
    modules: 6,
    desc: "Otomatiskan balas chat pelanggan, bikin deskripsi produk, dan hitung strategi harga pakai AI — dirancang untuk pemilik usaha kecil.",
    popular: false,
  },
  {
    id: "otomasi-kerja",
    title: "Otomatisasi Kerja dengan AI",
    category: "Produktivitas",
    level: "Menengah",
    price: 299000,
    oldPrice: 419000,
    rating: 4.7,
    reviews: 198,
    students: 1420,
    duration: "7 jam",
    modules: 9,
    desc: "Hubungkan beberapa tools AI supaya kerja rutin bisa jalan sendiri. Cocok untuk yang sudah paham dasar dan mau naik level.",
    popular: false,
  },
  {
    id: "ai-data-excel",
    title: "AI untuk Olah Data & Excel",
    category: "Skill Inti",
    level: "Menengah",
    price: 269000,
    oldPrice: 359000,
    rating: 4.6,
    reviews: 167,
    students: 980,
    duration: "5.5 jam",
    modules: 7,
    desc: "Minta AI bantu bikin rumus, rapikan data, dan baca laporan Excel dalam hitungan detik.",
    popular: false,
  },
  {
    id: "etika-ai",
    title: "Etika & Keamanan Menggunakan AI",
    category: "Dasar AI",
    level: "Pemula",
    price: 149000,
    oldPrice: 199000,
    rating: 4.9,
    reviews: 245,
    students: 1680,
    duration: "3 jam",
    modules: 5,
    desc: "Pahami batasan, risiko privasi, dan cara menggunakan AI secara bertanggung jawab sebelum melangkah lebih jauh.",
    popular: false,
  },
];

const TEACHER = {
  name: "Raka Pradipta",
  role: "AI Practitioner & Pengajar Melek Digital",
  bio: "8 tahun bekerja di bidang teknologi, kini fokus membantu 1000+ pemula di Indonesia jadi percaya diri memakai AI sehari-hari.",
};
